name: Build and Deploy Frontend
on:
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build frontend
        working-directory: frontend
        run: |
          npm install
          CI=false npm run build

      - name: Package zip in its own folder
        run: |
          mkdir -p deploy-package
          cd frontend/.next && zip -rq ../../deploy-package/next-build.zip . && cd ../..

      - name: Deploy zip via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./deploy-package/
          server-dir: ./
